---
global:
  scrape_interval: '5s'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
        - 'localhost:9090'

  - job_name: 'ui'
    static_configs:
      - targets:
        - 'ui:8000'

  - job_name: 'rabbitmq'
    static_configs:
      - targets:
        - 'rabbitmq:15672'
        - 'rabbitmq:5672'

  - job_name: 'node'
    static_configs:
      - targets:
        - 'node-exporter:9100'

  - job_name: 'mongod'
    static_configs:
      - targets:
        - 'post_db:27017'

  - job_name: 'cadvisor'
    static_configs:
      - targets:
        - 'cadvisor:8080'

rule_files:
  - "alerts.yml"

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"
