---
apiVersion: v1
kind: Service
metadata:
  name: post-db
  labels:
    app: search-engine
    component: mongo
    post_db: "true"
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: search-engine
    component: mongo
    post_db: "true"
