---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    app: search-engine
    component: mongo
    post-db: "true"
    ui-db: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-engine
      component: mongo
  template:
    metadata:
      name: mongo
      labels:
        app: search-engine
        component: mongo
        post-db: "true"
        ui-db: "true"
    spec:
      containers:
      - image: mongo:latest
        name: mongo
