---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  labels:
    app: search-engine
    component: ui
spec:
  replicas: 3
  selector:
    matchLabels:
      app: search-engine
      component: ui
  template:
    metadata:
      name: ui
      labels:
        app: search-engine
        component: ui
    spec:
      containers:
      - image: finrerty/ui
        name: ui
        env:
        - name: ENV
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
