- name: Add config for DB connection
  template:
    src: db_config.j2
    dest: "/home/{{ deploy_user }}/db_config"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"

- name: Copy puma.service.j2 file to systemd
  template:
    src: gunicorn.service.j2
    dest: "/etc/systemd/system/gunicorn.service"
    mode: '0755'
  notify: reload gunicorn
